# Stage 1: Build Wasm distribution
FROM gradle:8.11.1-jdk17 AS builder
WORKDIR /project
COPY --chown=gradle:gradle . /project
RUN gradle :webApp:wasmJsBrowserDistribution --no-daemon

# Stage 2: Serve using Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /project/webApp/build/dist/wasmJs/productionExecutable /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
