# JVM settings for build processes
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Enable parallel and configuration caching options
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin settings
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# Compose Multiplatform settings
org.jetbrains.compose.experimental.uikit.enabled=true

# Android settings
android.useAndroidX=true
android.enableJetifier=true
